p1 <- InputParam(id = "geneRank", type = "File", prefix = "--gene-ranking")
p2 <- InputParam(id = "gmt", type = "File", prefix = "--gmt-file")
p3 <- InputParam(id = "prefix", type = "string", prefix = "-n")
o1 <- OutputParam(id = "pouts", type = "File[]", glob = "$(inputs.prefix)*")

req1 <- requireDocker("quay.io/biocontainers/mageck:0.5.9.4--py38hed8969a_0")
mageck_pathway <- cwlProcess(baseCommand = c("mageck", "pathway"),
                             requirements = list(req1),
                             inputs = InputParamList(p1, p2, p3),
                             outputs = OutputParamList(o1))


mageck_pathway <- addMeta(
    mageck_pathway,
    label = "mageck_pathway",
    doc = "Determine if specific biological pathways or gene sets are significantly enriched with positively or negatively selected genes",
    inputLabels = c("geneRank","gmt","prefix"),
    inputDocs = c("The gene summary file (containing both positive and negative selection tests) generated by the gene test step. Pathway enrichment will be performed in both directions.","The pathway file in GMT format.","The prefix of the output file(s). Default sample1."),
    outputLabels = c("pouts"),
    outputDocs = c("The outputs generated"),
    extensions = list(
        author = "rworkflow team",
        date = "09-08-24",
        url = "https://sourceforge.net/p/mageck/wiki/Home/",
        example = paste()
    )
)
