p1 <- InputParam(id = "sam", type = "File")
o1 <- OutputParam(id = "strip", type = "File", glob = "*_stripped.sam")
req1 <- requireInitialWorkDir(listing = list("$(inputs.sam)"))
req2 <- requireDocker("hubentu/rrbs")
strip_sam <- cwlProcess(baseCommand = c("bash", "/opt/strip_bismark_sam.sh"),
                        requirements = list(req1, req2),
                        inputs = InputParamList(p1),
                        outputs = OutputParamList(o1))


strip_sam <- addMeta(
    strip_sam,
    label = "strip_sam",
    doc = "Simplify and clean up the SAM (Sequence Alignment/Map) files generated by Bismark by removing non-essential information.",
    inputLabels = c("sam"),
    inputDocs = c("Input Sam file"),
    outputLabels = c("strip"),
    outputDocs = c("Cleaned up sam file"),
    extensions = list(
        author = "rworkflow team",
        date = "09-08-24",
        url = "NA",
        example = paste()
    )
)
