## http://varscan.sourceforge.net
p1 <- InputParam(id = "npileup", type = "File", position = 1)
p2 <- InputParam(id = "tpileup", type = "File", position = 2)
p3 <- InputParam(id = "bname", type = "string", position = 3)
p4 <- InputParam(id = "vcfout", type = "boolean", prefix = "--output-vcf",
                 position = 4, default = TRUE)
o1 <- OutputParam(id = "snp", type = "File", glob = "$(inputs.bname).snp.vcf")
o2 <- OutputParam(id = "indel", type = "File", glob = "$(inputs.bname).indel.vcf")

req1 <- list(class = "DockerRequirement",
             dockerPull = "mgibio/varscan-cwl:v2.4.2-samtools1.3.1")

VarScan2_somatic <- cwlProcess(baseCommand = c("java", "-jar",
                                             "/opt/varscan/VarScan.jar", "somatic"),
                             requirements = list(req1),
                             inputs = InputParamList(p1, p2, p3, p4),
                             outputs = OutputParamList(o1, o2))


VarScan2_somatic <- addMeta(
    VarScan2_somatic,
    label = "VarScan2_somatic",
    doc = "VarScan2 tool designed for detecting somatic variants in paired tumor-normal samples from high-throughput sequencing data.",
    inputLabels = c("npileup","tpileup","bname","vcfout"),
    inputDocs = c("Normal sample pileup file used to establish a baseline for somatic variant calling.","Tumor sample pileup file used to identify somatic mutations.","Base name for output files, serving as a prefix for naming all output files generated by VarScan2.","Option to enable or disable VCF format output (set to 1 to output in VCF format)."),
    outputLabels = c("snp","indel"),
    outputDocs = c("A single nucleotide polymorphism (SNP), also known as a single nucleotide variant (SNV), is a genetic variant that involves a change of a single nucleotide base in the DNA sequence.","indel is a term used to refer to either an insertion or deletion of one or more bases in the DNA sequence."),
    extensions = list(
        author = "rworkflow team",
        date = "09-08-24",
        url = "http://varscan.sourceforge.net",
        example = paste()
    )
)
